# fly.toml file generated for red-firefly-2361 on 2022-12-07T18:13:42+02:00
app = "red-firefly-2361"

[experimental]
  enable_consul = true

[mounts]
  destination = "/mnt/sqlite"
  source = "drizzle"

[[services]]
  internal_port = 8787
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
