# fly.toml file generated for withered-violet-4754 on 2022-12-07T19:48:38+02:00

app = "withered-violet-4754"

[experimental]
  enable_consul = true

[mounts]
  destination = "/mnt/sqlite"
  source = "drizzle"

[[services]]
  internal_port = 8787
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
